content:
  - name: navigation
    label: Navigation
    type: file
    path: web/src/data/navigation.yml
    fields:
      - name: links
        label: Links
        type: object
        list: true
        fields:
          - name: label
            label: Label
            type: string
          - name: url
            label: URL
            type: string
